# Generated by Django 5.0 on 2023-12-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
